In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

data = np.random.randint(0, 1000, size=(5, 6))
df = pd.DataFrame(data, columns=['row_1', 'row_2', 'row_3','row_4','row_5','row_6'])
df.to_csv('./file.csv',index=False)

data=pd.read_csv('file.csv')
x=data.iloc[:,:].values
print(x.shape)

row_mean,column_mean=[],[]
var_row=0
cov=0
covar=[]
column_var=[]
var_column=0
sum=0
sum_column=0
sum_rows=0

(5, 6)

In [2]:
data

   row_1  row_2  row_3  row_4  row_5  row_6
0    732     97    601    233    789    826
1    205    289    180    256    981    239
2    267    350     22    922    783    572
3    982    103    557    134    334    865
4    936     67    912     79    960    891


#  Calculated Using Built In Functions

In [3]:
def StatisticsDescription():
    dataMean=data.mean(axis=1)
    dataSD=data.std(axis=1)
    dataVar=data.var(axis=1)
    dataMode=data.mode(axis=1)
    dataMedian=data.median(axis=1)
    dataCov=np.cov(data.to_numpy())
    print("*****************Values Calculated Using Built In Functions************************")
    print('Sum:')
    print(np.sum(x))
    print("Mean:")
    print(dataMean)
    print("Std Dev:")
    print(dataSD)
    print("Variance:")
    print(dataVar)
    print("Median:")
    print(dataMedian)
    print("Mode:")
    print(dataMode)
    print("Covariance")
    print(dataCov)
    print('Correlation:', np.corrcoef(x[:,1],x[:,2]))

In [4]:
StatisticsDescription()

*****************Values Calculated Using Built In Functions************************
Sum:
15164
Mean:
0    546.333333
1    358.333333
2    486.000000
3    495.833333
4    640.833333
dtype: float64
Std Dev:
0    308.103662
1    307.423920
2    336.883956
3    370.894819
4    440.464944
dtype: float64
Variance:
0     94927.866667
1     94509.466667
2    113490.800000
3    137562.966667
4    194009.366667
dtype: float64
Median:
0    666.5
1    247.5
2    461.0
3    445.5
4    901.5
dtype: float64
Mode:
     0    1    2    3    4    5
0   97  233  601  732  789  826
1  180  205  239  256  289  981
2   22  267  350  572  783  922
3  103  134  334  557  865  982
4   67   79  891  912  936  960
Covariance
[[ 94927.86666667  28545.46666667  -9081.4         89493.66666667
  130184.86666667]
 [ 28545.46666667  94509.46666667  51161.6        -33202.33333333
   34508.86666667]
 [ -9081.4         51161.6        113490.8        -51100.4
  -48214.8       ]
 [ 89493.66666667 -33202.33333333 -51100.4        137562.96666667
  125899.76666667]
 [130184.86666667  34508.86666667 -48214.8        125899.76666667
  194009.36666667]]
Correlation: [[ 1.         -0.95826702]
 [-0.95826702  1.        ]]

In [5]:
perc =[.20, .40, .60, .80]
desc = data.describe(percentiles = perc)

In [6]:
desc

            row_1      row_2       row_3       row_4       row_5       row_6
count    5.000000    5.00000    5.000000    5.000000    5.000000    5.000000
mean   624.400000  181.20000  454.400000  324.800000  769.400000  678.600000
std    367.485102  128.80295  354.852505  341.551899  260.406029  276.675442
min    205.000000   67.00000   22.000000   79.000000  334.000000  239.000000
20%    254.600000   91.00000  148.400000  123.000000  693.200000  505.400000
40%    546.000000  100.60000  406.200000  193.400000  786.600000  724.400000
50%    732.000000  103.00000  557.000000  233.000000  789.000000  826.000000
60%    813.600000  177.40000  574.600000  242.200000  857.400000  841.600000
80%    945.200000  301.20000  663.200000  389.200000  964.200000  870.200000
max    982.000000  350.00000  912.000000  922.000000  981.000000  891.000000


# Calculated Using Formula's - User Defined Functions

In [7]:
def sumOfData():
    sum=0
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            sum=sum+x[i][j]
    print('Sum Of All Fields:', sum)

In [8]:
def meanOfData():
    row_mean,column_mean=[],[]
    for i in range(x.shape[1]):
        sum_column=0
        for j in range(x.shape[0]):
            sum_column=sum_column+x[j][i]
        column_mean.append((sum_column/x.shape[0]))
    print('mean of All Columns Are: ', column_mean)
    for i in range(x.shape[0]):
        sum_rows=0
        for j in range(x.shape[1]):
            sum_rows=sum_rows+x[i][j]
        row_mean.append((sum_rows/x.shape[1]))
    print('mean of All Rows Are: ', row_mean)
    print("**********************")
    return(column_mean,row_mean)

In [9]:
def varianceStdDevOfData(column_mean,row_mean):
    column_var=[]
    for i in range(x.shape[1]):
        var_column=0
        for j in range(x.shape[0]):
            var_column=var_column+(x[j][i]-column_mean[i])**2
        column_var.append((var_column/x.shape[0]))
    print('Variance of All Columns Are: ', column_var)
    print('Standard Deviation of All Columns Are: ', np.sqrt(column_var))
    row_var=[]
    for i in range(x.shape[0]):
        var_row=0
        for j in range(x.shape[1]):
            var_row=var_row+(x[i][j]-row_mean[i])**2
        row_var.append((var_row/x.shape[1]))
    print('Variance of All Rows Are: ', row_var)
    print('Standard Deviation of All Rows Are: ', np.sqrt(row_var))
    print("**********************")
    return column_var

In [10]:
def medianOfData():
    row_median,column_median=[],[]
    for i in range(x.shape[1]):
        col_elem,row_elem=[],[]
        for j in range(x.shape[0]):
            col_elem.append(x[j][i])
        col_elem.sort()
        if(len(col_elem)%2==0):
            column_median.append((col_elem[math.floor((len(col_elem)-1)/2)]+col_elem[math.floor((len(col_elem)+1)/2)])/2)
        else:
             column_median.append(col_elem[math.floor(len(col_elem)/2)])
    print('median of All Columns Are: ', column_median)
    for i in range(x.shape[0]):
        col_elem,row_elem=[],[]
        for j in range(x.shape[1]):
            row_elem.append(x[i][j])
        row_elem.sort()
        if((len(row_elem)%2)==0):
            row_median.append((row_elem[math.floor((len(row_elem)-1)/2)]+row_elem[math.floor((len(row_elem)+1)/2)])/2)
        else:
            row_median.append(row_elem[math.floor(len(row_elem)/2)])
    print('median of All Rows Are: ', row_median)
    print("**********************")

In [11]:
def covarianceOfData(column_mean,row_mean):
    for i in range(x.shape[1]-1):
        cov=0
        for j in range(x.shape[0]):
            cov=cov+((x[j][i]-column_mean[i])*(x[j][i+1]-column_mean[i+1]))
        covar.append(cov/x.shape[0]-1)
    print('covariance by formula is ', covar)
    print("**********************")
    return covar

In [12]:
def correlationOfData(column_var,cov):
    corr=[]
    for i in range(x.shape[1]-1):
        corr.append(cov[i]/(math.sqrt(column_var[i]) * math.sqrt(column_var[i+1])))
    print('Correlation Is', corr)
    print("**********************")


# Menu For Integrating All The Functions

In [13]:
while(True):
    print("Select One From The Choice: ")
    print("1) Sum Of Data")
    print("2) Mean Of Data")
    print("3) Variance Of Data")
    print("4) Co-Variance Of Data")
    print("5) Correlation Of Data")
    print("6) Median Of Data")
    print("7) Exit")
    option = int(input('Choose an option: '))
    if option == 1:
        sumOfData()
    elif option == 2:
        result=meanOfData()
    elif option == 3:
        res=varianceStdDevOfData(result[0],result[1])
    elif option == 4:
        covar=covarianceOfData(result[0],result[1])
    elif option == 5:
        correlationOfData(res,covar)
    elif option == 6:
        medianOfData()
    elif option == 7:
        break

Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 1
Sum Of All Fields: 15164
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 2
mean of All Columns Are:  [624.4, 181.2, 454.4, 324.8, 769.4, 678.6]
mean of All Rows Are:  [546.3333333333334, 358.3333333333333, 486.0, 495.8333333333333, 640.8333333333334]
**********************
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 3
Variance of All Columns Are:  [108036.24000000002, 13272.159999999998, 100736.23999999999, 93326.16, 54249.04, 61239.44]
Standard Deviation of All Columns Are:  [328.68866728 115.20486101 317.38972888 305.49330598 232.91423314
 247.46603807]
Variance of All Rows Are:  [79106.55555555555, 78757.8888888889, 94575.66666666667, 114635.80555555555, 161674.47222222225]
Standard Deviation of All Rows Are:  [281.2588764  280.63835962 307.5315702  338.57909793 402.08764246]
**********************
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 4
covariance by formula is  [-35630.88, -35039.880000000005, -76973.52, 5596.880000000002, -26452.04]
**********************
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 5
Correlation Is [-0.9409596786990179, -0.9582943719142797, -0.7938652293261493, 0.07865897240762526, -0.45893115034532933]
**********************
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 6
median of All Columns Are:  [732, 103, 557, 233, 789, 826]
median of All Rows Are:  [666.5, 247.5, 461.0, 445.5, 901.5]
**********************
Select One From The Choice:
1) Sum Of Data
2) Mean Of Data
3) Variance Of Data
4) Co-Variance Of Data
5) Correlation Of Data
6) Median Of Data
7) Exit
Choose an option: 7